apiVersion: v1
kind: Service
metadata:
    name: "akskoamano-56ef"
    labels:
        app: "akskoamano-56ef"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "akskoamano-56ef"