on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: crkoamano.azurecr.io
        username: ${{ secrets.acr_crkoamano_username }}
        password: ${{ secrets.acr_crkoamano_password }}
    
    - name: Build and push react image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/calculator_react" -f  "calculator_react/Dockerfile" -t crkoamano.azurecr.io/akskoamano-react:${{ github.sha }} --label dockerfile-path=calculator_react/Dockerfile
        docker push crkoamano.azurecr.io/akskoamano-react:${{ github.sha }}  
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_akskoamano_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep simple-test | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace simple-test`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: simple-test
        container-registry-url: crkoamano.azurecr.io
        container-registry-username: ${{ secrets.acr_crkoamano_username }}
        container-registry-password: ${{ secrets.acr_crkoamano_password }}
        secret-name: akskoamanodockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: simple-test
        manifests: |
          manifests/full_calc.yaml
        images: |
          crkoamano.azurecr.io/akskoamano-react:${{ github.sha }}
          crkoamano.azurecr.io/akskoamano-flask:${{ github.sha }}
        imagepullsecrets: |
          akskoamanodockerauth
